# Generated by Django 4.1.4 on 2023-05-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=60)),
                ('experience', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
